---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r set_globals, echo=FALSE, results="hide"}
# Do echo the code, and show the results.
knitr::opts_chunk$set(echo = TRUE, results = "show")
```

## Loading and preprocessing the data

```{r}
df <- read.csv(unz("activity.zip", "activity.csv"), stringsAsFactors = FALSE)
```

## What is mean total number of steps taken per day?

```{r}
# 1. Make a histogram of the total number of steps taken each day

# Aggregate steps per day (excluding NA values)
daily_steps <- aggregate(steps ~ date, data = df, FUN = sum, na.rm = TRUE)

hist(daily_steps$steps,
     main = "Histogram of Total Daily Steps",
     xlab = "Total Steps Taken per Day",
     col = "skyblue",
     border = "white")
```

```{r}
# 2. Calculate and report the **mean** and **median** total number of steps taken per day

mean_steps <- mean(daily_steps$steps, na.rm = TRUE)
cat("Mean steps: ", mean_steps)
```

```{r}
median_steps <- median(daily_steps$steps, na.rm = TRUE)
cat("Median steps: ", median_steps)
```

## What is the average daily activity pattern?

```{r}
# 1. Make a time series plot (i.e. `type = "l"`) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

mean_interval_steps <- aggregate(steps ~ interval, data = df, FUN = mean, na.rm = TRUE)

plot(mean_interval_steps$interval, mean_interval_steps$steps,
     type = "l",                             # line plot
     xlab = "5-minute Interval",
     ylab = "Average Steps",
     main = "Average Daily Activity Pattern",
     col = "skyblue")
```

```{r}
# 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

max_steps <- mean_interval_steps[which.max(mean_interval_steps$steps), ]
cat("Max average steps occur at interval", max_steps$interval,
    "with", round(max_steps$steps, 2), "steps on average.\n")
```

## Imputing missing values

```{r}
# 1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with `NA`s)

# 2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

# 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

# 4. Make a histogram of the total number of steps taken each day and Calculate and report the **mean** and **median** total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
# 1. Create a new factor variable in the dataset with two levels -- "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

# 1. Make a panel plot containing a time series plot (i.e. `type = "l"`) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). The plot should look something like the following, which was created using **simulated data**:


```
